using System.Collections.Generic;
using System.Text;

namespace WrapGod.Generator;

/// <summary>
/// String-based source code generation helpers.
/// Produces interface and facade source text from <see cref="TypePlan"/> models.
/// </summary>
internal static class SourceEmitter
{
    private const string AutoGeneratedHeader = "// <auto-generated />";
    internal const string DefaultNamespace = "WrapGod.Generated";

    /// <summary>
    /// When <c>true</c>, the emitter wraps version-specific facade members
    /// with runtime availability checks (used in Adaptive mode).
    /// </summary>
    public static bool AdaptiveMode { get; set; }

    /// <summary>
    /// Emits an interface source file for the given type plan.
    /// The interface name follows the pattern <c>IWrapped{EffectiveName}</c>.
    /// Static types return <c>null</c> — they cannot implement interfaces.
    /// </summary>
    public static string? EmitInterface(TypePlan type, string outputNamespace = DefaultNamespace)
    {
        if (type.IsStatic)
            return null;
        var sb = new StringBuilder();
        sb.AppendLine(AutoGeneratedHeader);
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.Append("namespace ").Append(outputNamespace).AppendLine(";");
        sb.AppendLine();
        sb.Append("public interface IWrapped").Append(type.EffectiveName);
        AppendTypeGenericParameters(sb, type.GenericTypeParameters);
        sb.AppendLine();
        AppendTypeConstraintClauses(sb, type.GenericTypeParameters);
        sb.AppendLine("{");

        foreach (var member in type.Members)
        {
            // Skip static members -- interfaces model instance contracts
            if (member.IsStatic)
                continue;

            EmitInterfaceMember(sb, member);
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    /// <summary>
    /// Emits a facade/proxy class that implements the generated interface
    /// and delegates all calls to an inner instance of the original type.
    /// </summary>
    public static string EmitFacade(TypePlan type, string outputNamespace = DefaultNamespace)
    {
        if (type.IsStatic)
            return EmitStaticFacade(type, outputNamespace);

        string interfaceName = "IWrapped" + type.EffectiveName;
        string className = type.EffectiveName + "Facade";

        // Build generic suffixes for type names.
        var genericSuffix = BuildTypeGenericSuffix(type.GenericTypeParameters);

        var sb = new StringBuilder();
        sb.AppendLine(AutoGeneratedHeader);
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.Append("namespace ").Append(outputNamespace).AppendLine(";");
        sb.AppendLine();
        sb.Append("public sealed class ").Append(className).Append(genericSuffix);
        sb.Append(" : ").Append(interfaceName).AppendLine(genericSuffix);
        AppendTypeConstraintClauses(sb, type.GenericTypeParameters);
        sb.AppendLine("{");
        sb.Append("    private readonly ").Append(type.FullName).AppendLine(" _inner;");
        sb.AppendLine();
        sb.Append("    public ").Append(className).Append(genericSuffix)
            .Append('(').Append(type.FullName).AppendLine(" inner)");
        sb.AppendLine("    {");
        sb.AppendLine("        _inner = inner ?? throw new System.ArgumentNullException(nameof(inner));");
        sb.AppendLine("    }");

        foreach (var member in type.Members)
        {
            // Skip static members -- facade delegates to an instance
            if (member.IsStatic)
                continue;

            sb.AppendLine();
            EmitFacadeMember(sb, member);
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    /// <summary>
    /// Emits a static facade class that forwards calls to the original static type.
    /// Used for static extension method classes (e.g., Shouldly assertion extensions).
    /// </summary>
    private static string EmitStaticFacade(TypePlan type, string outputNamespace)
    {
        string className = type.EffectiveName;

        var sb = new StringBuilder();
        sb.AppendLine(AutoGeneratedHeader);
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.Append("namespace ").Append(outputNamespace).AppendLine(";");
        sb.AppendLine();
        sb.Append("public static class ").AppendLine(className);
        sb.AppendLine("{");

        foreach (var member in type.Members)
        {
            sb.AppendLine();
            EmitStaticFacadeMember(sb, member, type.FullName);
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    /// <summary>
    /// Emits a single static method that forwards to the original static type.
    /// Extension methods preserve the 'this' parameter for seamless consumer usage.
    /// </summary>
    private static void EmitStaticFacadeMember(StringBuilder sb, MemberPlan member, string sourceType)
    {
        if (member.Kind == "property")
        {
            // Static properties: forward via getter/setter
            sb.Append("    public static ").Append(member.ReturnType).Append(' ').Append(member.EffectiveName);
            if (member.HasGetter && !member.HasSetter)
            {
                sb.Append(" => ").Append(sourceType).Append('.').Append(member.Name).AppendLine(";");
            }
            else
            {
                sb.AppendLine();
                sb.AppendLine("    {");
                if (member.HasGetter)
                    sb.Append("        get => ").Append(sourceType).Append('.').Append(member.Name).AppendLine(";");
                if (member.HasSetter)
                    sb.Append("        set => ").Append(sourceType).Append('.').Append(member.Name).AppendLine(" = value;");
                sb.AppendLine("    }");
            }
            return;
        }

        // Static method — check if first parameter is 'this' (extension method)
        bool isExtension = member.Parameters.Count > 0 && member.Parameters[0].IsThis;
        string returnType = NormalizeReturnType(member.ReturnType);
        bool isVoid = returnType == "void";

        sb.Append("    public static ").Append(returnType).Append(' ').Append(member.EffectiveName);
        AppendGenericParameters(sb, member.GenericParameters);
        sb.Append('(');

        // Emit parameters (preserve 'this' for extension methods)
        for (int i = 0; i < member.Parameters.Count; i++)
        {
            if (i > 0) sb.Append(", ");
            var p = member.Parameters[i];
            if (i == 0 && isExtension) sb.Append("this ");
            sb.Append(NormalizeTypeName(p.Type)).Append(' ').Append(p.Name);
        }
        sb.Append(')');
        AppendGenericConstraints(sb, member.GenericParameters);
        sb.AppendLine();

        // Emit forwarding body
        if (isVoid)
        {
            sb.Append("        { ").Append(sourceType).Append('.').Append(member.Name);
        }
        else
        {
            sb.Append("        => ").Append(sourceType).Append('.').Append(member.Name);
        }
        AppendGenericParameters(sb, member.GenericParameters);
        sb.Append('(');
        for (int i = 0; i < member.Parameters.Count; i++)
        {
            if (i > 0) sb.Append(", ");
            sb.Append(member.Parameters[i].Name);
        }
        if (isVoid)
            sb.AppendLine("); }");
        else
            sb.AppendLine(");");
    }

    private static void EmitInterfaceMember(StringBuilder sb, MemberPlan member)
    {
        if (member.Kind == "property")
        {
            sb.Append("    ").Append(member.ReturnType).Append(' ').Append(member.EffectiveName).Append(" { ");
            if (member.HasGetter)
            {
                sb.Append("get; ");
            }

            if (member.HasSetter)
            {
                sb.Append("set; ");
            }

            sb.AppendLine("}");
        }
        else
        {
            // Method
            sb.Append("    ").Append(member.ReturnType).Append(' ').Append(member.EffectiveName);
            AppendGenericParameters(sb, member.GenericParameters);
            sb.Append('(');
            AppendParameters(sb, member.Parameters);
            sb.AppendLine(");");
        }
    }

    private static void EmitFacadeMember(StringBuilder sb, MemberPlan member)
    {
        bool needsGuard = AdaptiveMode && member.IntroducedIn != null;

        if (member.Kind == "property")
        {
            sb.Append("    public ").Append(member.ReturnType).Append(' ').Append(member.EffectiveName);
            sb.AppendLine();
            sb.AppendLine("    {");
            if (member.HasGetter)
            {
                if (needsGuard)
                {
                    EmitVersionGuardedPropertyGetter(sb, member);
                }
                else
                {
                    sb.Append("        get => _inner.").Append(member.Name).AppendLine(";");
                }
            }

            if (member.HasSetter)
            {
                if (needsGuard)
                {
                    EmitVersionGuardedPropertySetter(sb, member);
                }
                else
                {
                    sb.Append("        set => _inner.").Append(member.Name).AppendLine(" = value;");
                }
            }

            sb.AppendLine("    }");
        }
        else
        {
            if (needsGuard)
            {
                EmitVersionGuardedMethod(sb, member);
            }
            else
            {
                // Method -- expression-bodied forwarding works for both void and non-void
                sb.Append("    public ").Append(member.ReturnType).Append(' ').Append(member.EffectiveName);
                AppendGenericParameters(sb, member.GenericParameters);
                sb.Append('(');
                AppendParameters(sb, member.Parameters);
                sb.AppendLine(")");
                sb.Append("        => _inner.").Append(member.Name);
                AppendGenericParameters(sb, member.GenericParameters);
                sb.Append('(');
                AppendArguments(sb, member.Parameters);
                sb.AppendLine(");");
            }
        }
    }

    private static string BuildAvailabilityComment(MemberPlan member)
    {
        var parts = new StringBuilder();
        parts.Append("Available since ").Append(member.IntroducedIn);
        if (member.RemovedIn != null)
        {
            parts.Append(", removed in ").Append(member.RemovedIn);
        }

        return parts.ToString();
    }

    private static void EmitVersionGuardedPropertyGetter(StringBuilder sb, MemberPlan member)
    {
        sb.Append("        // ").AppendLine(BuildAvailabilityComment(member));
        sb.AppendLine("        get");
        sb.AppendLine("        {");
        sb.Append("            if (!WrapGodVersionHelper.IsMemberAvailable(\"")
            .Append(member.IntroducedIn).Append("\", ");
        if (member.RemovedIn != null)
            sb.Append('"').Append(member.RemovedIn).Append('"');
        else
            sb.Append("null");
        sb.AppendLine("))");
        sb.Append("                throw new System.PlatformNotSupportedException(\"")
            .Append(member.Name).AppendLine(" is not available in the current version.\");");
        sb.Append("            return _inner.").Append(member.Name).AppendLine(";");
        sb.AppendLine("        }");
    }

    private static void EmitVersionGuardedPropertySetter(StringBuilder sb, MemberPlan member)
    {
        sb.Append("        // ").AppendLine(BuildAvailabilityComment(member));
        sb.AppendLine("        set");
        sb.AppendLine("        {");
        sb.Append("            if (!WrapGodVersionHelper.IsMemberAvailable(\"")
            .Append(member.IntroducedIn).Append("\", ");
        if (member.RemovedIn != null)
            sb.Append('"').Append(member.RemovedIn).Append('"');
        else
            sb.Append("null");
        sb.AppendLine("))");
        sb.Append("                throw new System.PlatformNotSupportedException(\"")
            .Append(member.Name).AppendLine(" is not available in the current version.\");");
        sb.Append("            _inner.").Append(member.Name).AppendLine(" = value;");
        sb.AppendLine("        }");
    }

    private static void EmitVersionGuardedMethod(StringBuilder sb, MemberPlan member)
    {
        sb.Append("    // ").AppendLine(BuildAvailabilityComment(member));
        sb.Append("    public ").Append(member.ReturnType).Append(' ').Append(member.EffectiveName);
        AppendGenericParameters(sb, member.GenericParameters);
        sb.Append('(');
        AppendParameters(sb, member.Parameters);
        sb.AppendLine(")");
        sb.AppendLine("    {");
        sb.Append("        if (!WrapGodVersionHelper.IsMemberAvailable(\"")
            .Append(member.IntroducedIn).Append("\", ");
        if (member.RemovedIn != null)
            sb.Append('"').Append(member.RemovedIn).Append('"');
        else
            sb.Append("null");
        sb.AppendLine("))");
        sb.Append("            throw new System.PlatformNotSupportedException(\"")
            .Append(member.Name).AppendLine(" is not available in the current version.\");");

        bool isVoid = member.ReturnType == "void" || member.ReturnType == "System.Void";
        sb.Append("        ");
        if (!isVoid) sb.Append("return ");
        sb.Append("_inner.").Append(member.Name);
        AppendGenericParameters(sb, member.GenericParameters);
        sb.Append('(');
        AppendArguments(sb, member.Parameters);
        sb.AppendLine(");");
        sb.AppendLine("    }");
    }

    /// <summary>Maps fully-qualified CLR type names to C# keyword aliases.</summary>
    private static readonly Dictionary<string, string> TypeAliases = new()
    {
        ["System.Void"] = "void",
        ["System.Boolean"] = "bool",
        ["System.Byte"] = "byte",
        ["System.SByte"] = "sbyte",
        ["System.Char"] = "char",
        ["System.Decimal"] = "decimal",
        ["System.Double"] = "double",
        ["System.Single"] = "float",
        ["System.Int32"] = "int",
        ["System.UInt32"] = "uint",
        ["System.Int64"] = "long",
        ["System.UInt64"] = "ulong",
        ["System.Int16"] = "short",
        ["System.UInt16"] = "ushort",
        ["System.Object"] = "object",
        ["System.String"] = "string",
    };

    private static string NormalizeReturnType(string type)
        => TypeAliases.TryGetValue(type, out var alias) ? alias : type;

    private static string NormalizeTypeName(string type)
    {
        // Handle nullable and generic types: normalize the inner type
        foreach (var kv in TypeAliases)
        {
            if (type == kv.Key) return kv.Value;
            type = type.Replace(kv.Key, kv.Value);
        }
        return type;
    }

    private static void AppendGenericParameters(StringBuilder sb, IReadOnlyList<string> genericParameters)
    {
        if (genericParameters.Count == 0)
            return;

        sb.Append('<');
        for (int i = 0; i < genericParameters.Count; i++)
        {
            if (i > 0) sb.Append(", ");
            sb.Append(genericParameters[i]);
        }

        sb.Append('>');
    }

    private static void AppendGenericParameters(StringBuilder sb, IReadOnlyList<GenericTypeParameterPlan> genericParameters)
    {
        if (genericParameters.Count == 0)
            return;

        sb.Append('<');
        for (int i = 0; i < genericParameters.Count; i++)
        {
            if (i > 0) sb.Append(", ");
            sb.Append(genericParameters[i].Name);
        }

        sb.Append('>');
    }

    private static void AppendGenericConstraints(StringBuilder sb, IReadOnlyList<GenericTypeParameterPlan> genericParameters)
    {
        foreach (var gp in genericParameters)
        {
            if (gp.Constraints.Count == 0)
                continue;

            sb.Append(" where ").Append(gp.Name).Append(" : ");
            for (int i = 0; i < gp.Constraints.Count; i++)
            {
                if (i > 0) sb.Append(", ");
                sb.Append(NormalizeTypeName(gp.Constraints[i]));
            }
        }
    }

    private static void AppendParameters(StringBuilder sb, IReadOnlyList<ParameterPlan> parameters)
    {
        for (int i = 0; i < parameters.Count; i++)
        {
            if (i > 0) sb.Append(", ");
            if (parameters[i].Modifier.Length > 0)
            {
                sb.Append(parameters[i].Modifier).Append(' ');
            }

            sb.Append(parameters[i].Type).Append(' ').Append(parameters[i].Name);
        }
    }

    private static void AppendArguments(StringBuilder sb, IReadOnlyList<ParameterPlan> parameters)
    {
        for (int i = 0; i < parameters.Count; i++)
        {
            if (i > 0) sb.Append(", ");

            // ref/out must be forwarded with the same keyword
            string mod = parameters[i].Modifier;
            if (mod == "ref" || mod == "out")
            {
                sb.Append(mod).Append(' ');
            }

            sb.Append(parameters[i].Name);
        }
    }

    // ── Type-level generic helpers ──────────────────────────────────

    private static void AppendTypeGenericParameters(
        StringBuilder sb, IReadOnlyList<GenericTypeParameterPlan> typeParams)
    {
        if (typeParams.Count == 0)
            return;

        sb.Append('<');
        for (int i = 0; i < typeParams.Count; i++)
        {
            if (i > 0) sb.Append(", ");
            sb.Append(typeParams[i].Name);
        }

        sb.Append('>');
    }

    private static string BuildTypeGenericSuffix(IReadOnlyList<GenericTypeParameterPlan> typeParams)
    {
        if (typeParams.Count == 0)
            return string.Empty;

        var sb = new StringBuilder();
        sb.Append('<');
        for (int i = 0; i < typeParams.Count; i++)
        {
            if (i > 0) sb.Append(", ");
            sb.Append(typeParams[i].Name);
        }

        sb.Append('>');
        return sb.ToString();
    }

    private static void AppendTypeConstraintClauses(
        StringBuilder sb, IReadOnlyList<GenericTypeParameterPlan> typeParams)
    {
        foreach (var param in typeParams)
        {
            if (param.Constraints.Count == 0)
                continue;

            sb.Append("    where ").Append(param.Name).Append(" : ");
            for (int i = 0; i < param.Constraints.Count; i++)
            {
                if (i > 0) sb.Append(", ");
                sb.Append(param.Constraints[i]);
            }

            sb.AppendLine();
        }
    }
}
