using System.Collections.Generic;
using System.Text;

namespace WrapGod.Generator;

/// <summary>
/// String-based source code generation helpers.
/// Produces interface and facade source text from <see cref="TypePlan"/> models.
/// </summary>
internal static class SourceEmitter
{
    private const string AutoGeneratedHeader = "// <auto-generated />";
    private const string GeneratedNamespace = "WrapGod.Generated";

    /// <summary>
    /// Emits an interface source file for the given type plan.
    /// The interface name follows the pattern <c>IWrapped{TypeName}</c>.
    /// </summary>
    public static string EmitInterface(TypePlan type)
    {
        var sb = new StringBuilder();
        sb.AppendLine(AutoGeneratedHeader);
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.Append("namespace ").Append(GeneratedNamespace).AppendLine(";");
        sb.AppendLine();
        sb.Append("public interface IWrapped").AppendLine(type.Name);
        sb.AppendLine("{");

        foreach (var member in type.Members)
        {
            // Skip static members -- interfaces model instance contracts
            if (member.IsStatic)
                continue;

            EmitInterfaceMember(sb, member);
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    /// <summary>
    /// Emits a facade/proxy class that implements the generated interface
    /// and delegates all calls to an inner instance of the original type.
    /// </summary>
    public static string EmitFacade(TypePlan type)
    {
        string interfaceName = "IWrapped" + type.Name;
        string className = type.Name + "Facade";

        var sb = new StringBuilder();
        sb.AppendLine(AutoGeneratedHeader);
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.Append("namespace ").Append(GeneratedNamespace).AppendLine(";");
        sb.AppendLine();
        sb.Append("public sealed class ").Append(className).Append(" : ").AppendLine(interfaceName);
        sb.AppendLine("{");
        sb.Append("    private readonly ").Append(type.FullName).AppendLine(" _inner;");
        sb.AppendLine();
        sb.Append("    public ").Append(className).Append('(').Append(type.FullName).AppendLine(" inner)");
        sb.AppendLine("    {");
        sb.AppendLine("        _inner = inner ?? throw new System.ArgumentNullException(nameof(inner));");
        sb.AppendLine("    }");

        foreach (var member in type.Members)
        {
            // Skip static members -- facade delegates to an instance
            if (member.IsStatic)
                continue;

            sb.AppendLine();
            EmitFacadeMember(sb, member);
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void EmitInterfaceMember(StringBuilder sb, MemberPlan member)
    {
        if (member.Kind == "property")
        {
            sb.Append("    ").Append(member.ReturnType).Append(' ').Append(member.Name).Append(" { ");
            if (member.HasGetter)
            {
                sb.Append("get; ");
            }

            if (member.HasSetter)
            {
                sb.Append("set; ");
            }

            sb.AppendLine("}");
        }
        else
        {
            // Method
            sb.Append("    ").Append(member.ReturnType).Append(' ').Append(member.Name);
            AppendGenericParameters(sb, member.GenericParameters);
            sb.Append('(');
            AppendParameters(sb, member.Parameters);
            sb.AppendLine(");");
        }
    }

    private static void EmitFacadeMember(StringBuilder sb, MemberPlan member)
    {
        if (member.Kind == "property")
        {
            sb.Append("    public ").Append(member.ReturnType).Append(' ').Append(member.Name);
            sb.AppendLine();
            sb.AppendLine("    {");
            if (member.HasGetter)
            {
                sb.Append("        get => _inner.").Append(member.Name).AppendLine(";");
            }

            if (member.HasSetter)
            {
                sb.Append("        set => _inner.").Append(member.Name).AppendLine(" = value;");
            }

            sb.AppendLine("    }");
        }
        else
        {
            // Method -- expression-bodied forwarding works for both void and non-void
            sb.Append("    public ").Append(member.ReturnType).Append(' ').Append(member.Name);
            AppendGenericParameters(sb, member.GenericParameters);
            sb.Append('(');
            AppendParameters(sb, member.Parameters);
            sb.AppendLine(")");
            sb.Append("        => _inner.").Append(member.Name);
            AppendGenericParameters(sb, member.GenericParameters);
            sb.Append('(');
            AppendArguments(sb, member.Parameters);
            sb.AppendLine(");");
        }
    }

    private static void AppendGenericParameters(StringBuilder sb, IReadOnlyList<string> genericParameters)
    {
        if (genericParameters.Count == 0)
            return;

        sb.Append('<');
        for (int i = 0; i < genericParameters.Count; i++)
        {
            if (i > 0) sb.Append(", ");
            sb.Append(genericParameters[i]);
        }

        sb.Append('>');
    }

    private static void AppendParameters(StringBuilder sb, IReadOnlyList<ParameterPlan> parameters)
    {
        for (int i = 0; i < parameters.Count; i++)
        {
            if (i > 0) sb.Append(", ");
            if (parameters[i].Modifier.Length > 0)
            {
                sb.Append(parameters[i].Modifier).Append(' ');
            }

            sb.Append(parameters[i].Type).Append(' ').Append(parameters[i].Name);
        }
    }

    private static void AppendArguments(StringBuilder sb, IReadOnlyList<ParameterPlan> parameters)
    {
        for (int i = 0; i < parameters.Count; i++)
        {
            if (i > 0) sb.Append(", ");

            // ref/out must be forwarded with the same keyword
            string mod = parameters[i].Modifier;
            if (mod == "ref" || mod == "out")
            {
                sb.Append(mod).Append(' ');
            }

            sb.Append(parameters[i].Name);
        }
    }
}
