using System.Collections.Generic;
using System.Text;

namespace WrapGod.Generator;

/// <summary>
/// String-based source code generation helpers.
/// Produces interface and facade source text from <see cref="TypePlan"/> models.
/// </summary>
internal static class SourceEmitter
{
    private const string AutoGeneratedHeader = "// <auto-generated />";
    private const string GeneratedNamespace = "WrapGod.Generated";

    /// <summary>
    /// When <c>true</c>, the emitter wraps version-specific facade members
    /// with runtime availability checks (used in Adaptive mode).
    /// </summary>
    public static bool AdaptiveMode { get; set; }

    /// <summary>
    /// Emits an interface source file for the given type plan.
    /// The interface name follows the pattern <c>IWrapped{EffectiveName}</c>.
    /// </summary>
    public static string EmitInterface(TypePlan type)
    {
        var sb = new StringBuilder();
        sb.AppendLine(AutoGeneratedHeader);
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.Append("namespace ").Append(GeneratedNamespace).AppendLine(";");
        sb.AppendLine();
        sb.Append("public interface IWrapped").Append(type.EffectiveName);
        AppendTypeGenericParameters(sb, type.GenericTypeParameters);
        sb.AppendLine();
        AppendTypeConstraintClauses(sb, type.GenericTypeParameters);
        sb.AppendLine("{");

        foreach (var member in type.Members)
        {
            // Skip static members -- interfaces model instance contracts
            if (member.IsStatic)
                continue;

            EmitInterfaceMember(sb, member);
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    /// <summary>
    /// Emits a facade/proxy class that implements the generated interface
    /// and delegates all calls to an inner instance of the original type.
    /// </summary>
    public static string EmitFacade(TypePlan type)
    {
        string interfaceName = "IWrapped" + type.EffectiveName;
        string className = type.EffectiveName + "Facade";

        // Build generic suffixes for type names.
        var genericSuffix = BuildTypeGenericSuffix(type.GenericTypeParameters);

        var sb = new StringBuilder();
        sb.AppendLine(AutoGeneratedHeader);
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.Append("namespace ").Append(GeneratedNamespace).AppendLine(";");
        sb.AppendLine();
        sb.Append("public sealed class ").Append(className).Append(genericSuffix);
        sb.Append(" : ").Append(interfaceName).AppendLine(genericSuffix);
        AppendTypeConstraintClauses(sb, type.GenericTypeParameters);
        sb.AppendLine("{");
        sb.Append("    private readonly ").Append(type.FullName).AppendLine(" _inner;");
        sb.AppendLine();
        sb.Append("    public ").Append(className).Append(genericSuffix)
            .Append('(').Append(type.FullName).AppendLine(" inner)");
        sb.AppendLine("    {");
        sb.AppendLine("        _inner = inner ?? throw new System.ArgumentNullException(nameof(inner));");
        sb.AppendLine("    }");

        foreach (var member in type.Members)
        {
            // Skip static members -- facade delegates to an instance
            if (member.IsStatic)
                continue;

            sb.AppendLine();
            EmitFacadeMember(sb, member);
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void EmitInterfaceMember(StringBuilder sb, MemberPlan member)
    {
        if (member.Kind == "property")
        {
            sb.Append("    ").Append(member.ReturnType).Append(' ').Append(member.EffectiveName).Append(" { ");
            if (member.HasGetter)
            {
                sb.Append("get; ");
            }

            if (member.HasSetter)
            {
                sb.Append("set; ");
            }

            sb.AppendLine("}");
        }
        else
        {
            // Method
            sb.Append("    ").Append(member.ReturnType).Append(' ').Append(member.EffectiveName);
            AppendGenericParameters(sb, member.GenericParameters);
            sb.Append('(');
            AppendParameters(sb, member.Parameters);
            sb.AppendLine(");");
        }
    }

    private static void EmitFacadeMember(StringBuilder sb, MemberPlan member)
    {
        bool needsGuard = AdaptiveMode && member.IntroducedIn != null;

        if (member.Kind == "property")
        {
            sb.Append("    public ").Append(member.ReturnType).Append(' ').Append(member.EffectiveName);
            sb.AppendLine();
            sb.AppendLine("    {");
            if (member.HasGetter)
            {
                if (needsGuard)
                {
                    EmitVersionGuardedPropertyGetter(sb, member);
                }
                else
                {
                    sb.Append("        get => _inner.").Append(member.Name).AppendLine(";");
                }
            }

            if (member.HasSetter)
            {
                if (needsGuard)
                {
                    EmitVersionGuardedPropertySetter(sb, member);
                }
                else
                {
                    sb.Append("        set => _inner.").Append(member.Name).AppendLine(" = value;");
                }
            }

            sb.AppendLine("    }");
        }
        else
        {
            if (needsGuard)
            {
                EmitVersionGuardedMethod(sb, member);
            }
            else
            {
                // Method -- expression-bodied forwarding works for both void and non-void
                sb.Append("    public ").Append(member.ReturnType).Append(' ').Append(member.EffectiveName);
                AppendGenericParameters(sb, member.GenericParameters);
                sb.Append('(');
                AppendParameters(sb, member.Parameters);
                sb.AppendLine(")");
                sb.Append("        => _inner.").Append(member.Name);
                AppendGenericParameters(sb, member.GenericParameters);
                sb.Append('(');
                AppendArguments(sb, member.Parameters);
                sb.AppendLine(");");
            }
        }
    }

    private static string BuildAvailabilityComment(MemberPlan member)
    {
        var parts = new StringBuilder();
        parts.Append("Available since ").Append(member.IntroducedIn);
        if (member.RemovedIn != null)
        {
            parts.Append(", removed in ").Append(member.RemovedIn);
        }

        return parts.ToString();
    }

    private static void EmitVersionGuardedPropertyGetter(StringBuilder sb, MemberPlan member)
    {
        sb.Append("        // ").AppendLine(BuildAvailabilityComment(member));
        sb.AppendLine("        get");
        sb.AppendLine("        {");
        sb.Append("            if (!WrapGodVersionHelper.IsMemberAvailable(\"")
            .Append(member.IntroducedIn).Append("\", ");
        if (member.RemovedIn != null)
            sb.Append('"').Append(member.RemovedIn).Append('"');
        else
            sb.Append("null");
        sb.AppendLine("))");
        sb.Append("                throw new System.PlatformNotSupportedException(\"")
            .Append(member.Name).AppendLine(" is not available in the current version.\");");
        sb.Append("            return _inner.").Append(member.Name).AppendLine(";");
        sb.AppendLine("        }");
    }

    private static void EmitVersionGuardedPropertySetter(StringBuilder sb, MemberPlan member)
    {
        sb.Append("        // ").AppendLine(BuildAvailabilityComment(member));
        sb.AppendLine("        set");
        sb.AppendLine("        {");
        sb.Append("            if (!WrapGodVersionHelper.IsMemberAvailable(\"")
            .Append(member.IntroducedIn).Append("\", ");
        if (member.RemovedIn != null)
            sb.Append('"').Append(member.RemovedIn).Append('"');
        else
            sb.Append("null");
        sb.AppendLine("))");
        sb.Append("                throw new System.PlatformNotSupportedException(\"")
            .Append(member.Name).AppendLine(" is not available in the current version.\");");
        sb.Append("            _inner.").Append(member.Name).AppendLine(" = value;");
        sb.AppendLine("        }");
    }

    private static void EmitVersionGuardedMethod(StringBuilder sb, MemberPlan member)
    {
        sb.Append("    // ").AppendLine(BuildAvailabilityComment(member));
        sb.Append("    public ").Append(member.ReturnType).Append(' ').Append(member.EffectiveName);
        AppendGenericParameters(sb, member.GenericParameters);
        sb.Append('(');
        AppendParameters(sb, member.Parameters);
        sb.AppendLine(")");
        sb.AppendLine("    {");
        sb.Append("        if (!WrapGodVersionHelper.IsMemberAvailable(\"")
            .Append(member.IntroducedIn).Append("\", ");
        if (member.RemovedIn != null)
            sb.Append('"').Append(member.RemovedIn).Append('"');
        else
            sb.Append("null");
        sb.AppendLine("))");
        sb.Append("            throw new System.PlatformNotSupportedException(\"")
            .Append(member.Name).AppendLine(" is not available in the current version.\");");

        bool isVoid = member.ReturnType == "void" || member.ReturnType == "System.Void";
        sb.Append("        ");
        if (!isVoid) sb.Append("return ");
        sb.Append("_inner.").Append(member.Name);
        AppendGenericParameters(sb, member.GenericParameters);
        sb.Append('(');
        AppendArguments(sb, member.Parameters);
        sb.AppendLine(");");
        sb.AppendLine("    }");
    }

    private static void AppendGenericParameters(StringBuilder sb, IReadOnlyList<string> genericParameters)
    {
        if (genericParameters.Count == 0)
            return;

        sb.Append('<');
        for (int i = 0; i < genericParameters.Count; i++)
        {
            if (i > 0) sb.Append(", ");
            sb.Append(genericParameters[i]);
        }

        sb.Append('>');
    }

    private static void AppendParameters(StringBuilder sb, IReadOnlyList<ParameterPlan> parameters)
    {
        for (int i = 0; i < parameters.Count; i++)
        {
            if (i > 0) sb.Append(", ");
            if (parameters[i].Modifier.Length > 0)
            {
                sb.Append(parameters[i].Modifier).Append(' ');
            }

            sb.Append(parameters[i].Type).Append(' ').Append(parameters[i].Name);
        }
    }

    private static void AppendArguments(StringBuilder sb, IReadOnlyList<ParameterPlan> parameters)
    {
        for (int i = 0; i < parameters.Count; i++)
        {
            if (i > 0) sb.Append(", ");

            // ref/out must be forwarded with the same keyword
            string mod = parameters[i].Modifier;
            if (mod == "ref" || mod == "out")
            {
                sb.Append(mod).Append(' ');
            }

            sb.Append(parameters[i].Name);
        }
    }

    // ── Type-level generic helpers ──────────────────────────────────

    private static void AppendTypeGenericParameters(
        StringBuilder sb, IReadOnlyList<GenericTypeParameterPlan> typeParams)
    {
        if (typeParams.Count == 0)
            return;

        sb.Append('<');
        for (int i = 0; i < typeParams.Count; i++)
        {
            if (i > 0) sb.Append(", ");
            sb.Append(typeParams[i].Name);
        }

        sb.Append('>');
    }

    private static string BuildTypeGenericSuffix(IReadOnlyList<GenericTypeParameterPlan> typeParams)
    {
        if (typeParams.Count == 0)
            return string.Empty;

        var sb = new StringBuilder();
        sb.Append('<');
        for (int i = 0; i < typeParams.Count; i++)
        {
            if (i > 0) sb.Append(", ");
            sb.Append(typeParams[i].Name);
        }

        sb.Append('>');
        return sb.ToString();
    }

    private static void AppendTypeConstraintClauses(
        StringBuilder sb, IReadOnlyList<GenericTypeParameterPlan> typeParams)
    {
        foreach (var param in typeParams)
        {
            if (param.Constraints.Count == 0)
                continue;

            sb.Append("    where ").Append(param.Name).Append(" : ");
            for (int i = 0; i < param.Constraints.Count; i++)
            {
                if (i > 0) sb.Append(", ");
                sb.Append(param.Constraints[i]);
            }

            sb.AppendLine();
        }
    }
}
