using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace WrapGod.Generator;

[Generator]
public sealed class WrapGodIncrementalGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var manifestFiles = context.AdditionalTextsProvider
            .Where(static file => file.Path.EndsWith("wrapgod.manifest.json", StringComparison.OrdinalIgnoreCase))
            .Select(static (file, ct) => file.GetText(ct)?.ToString() ?? string.Empty);

        var combined = context.CompilationProvider.Combine(manifestFiles.Collect());

        context.RegisterSourceOutput(combined, static (spc, input) =>
        {
            var (compilation, manifests) = input;
            var assemblyName = compilation.AssemblyName ?? "WrapGod";

            var source = BuildSkeletonSource(assemblyName, manifests.Length);
            spc.AddSource("WrapGod.Generator.Skeleton.g.cs", SourceText.From(source, Encoding.UTF8));
        });
    }

    private static string BuildSkeletonSource(string assemblyName, int manifestCount)
    {
        return $$"""
        // <auto-generated />
        namespace WrapGod.Generated;

        internal static class WrapGodGeneratorMetadata
        {
            public const string AssemblyName = "{{assemblyName}}";
            public const int ManifestCount = {{manifestCount}};
        }
        """;
    }
}
