using System;
using System.Collections.Generic;

namespace WrapGod.TypeMap.Generation;

/// <summary>
/// Takes a <see cref="TypeMappingPlan"/> and generates C# static mapper classes.
/// Each <see cref="TypeMapping"/> produces a mapper class with a static
/// <c>Map(source)</c> method that converts from source to destination type.
/// </summary>
public static class TypeMapperEmitter
{
    private const string AutoGeneratedHeader = "// <auto-generated />";
    private const string GeneratedNamespace = "WrapGod.Generated.Mappers";

    /// <summary>
    /// Emit all mapper classes for the given plan as a single compilation unit.
    /// </summary>
    public static string Emit(TypeMappingPlan plan)
    {
        var sb = new MapperSourceBuilder();
        sb.AppendLine(AutoGeneratedHeader);
        sb.AppendLine("#nullable enable");
        sb.BlankLine();
        sb.AppendLine("namespace " + GeneratedNamespace + ";");

        foreach (var mapping in plan.Mappings)
        {
            sb.BlankLine();
            EmitMapper(sb, mapping);
        }

        return sb.ToString();
    }

    /// <summary>
    /// Emit a single mapper class for the given <see cref="TypeMapping"/>.
    /// </summary>
    public static string EmitSingle(TypeMapping mapping)
    {
        var sb = new MapperSourceBuilder();
        sb.AppendLine(AutoGeneratedHeader);
        sb.AppendLine("#nullable enable");
        sb.BlankLine();
        sb.AppendLine("namespace " + GeneratedNamespace + ";");
        sb.BlankLine();
        EmitMapper(sb, mapping);
        return sb.ToString();
    }

    private static void EmitMapper(MapperSourceBuilder sb, TypeMapping mapping)
    {
        string className = SafeClassName(mapping.SourceType) + "Mapper";
        sb.AppendLine("public static class " + className);
        sb.OpenBrace();

        sb.AppendLine("public static " + mapping.DestinationType + " Map(" + mapping.SourceType + " source)");
        sb.OpenBrace();

        switch (mapping.Kind)
        {
            case TypeMappingKind.ObjectMapping:
                EmitObjectMapping(sb, mapping);
                break;
            case TypeMappingKind.Enum:
                EmitEnumMapping(sb, mapping);
                break;
            case TypeMappingKind.Collection:
                EmitCollectionMapping(sb, mapping);
                break;
            case TypeMappingKind.Nullable:
                EmitNullableMapping(sb, mapping);
                break;
            case TypeMappingKind.Custom:
                EmitCustomMapping(sb, mapping);
                break;
            default:
                throw new NotSupportedException("Unsupported mapping kind: " + mapping.Kind);
        }

        sb.CloseBrace(); // Map method
        sb.CloseBrace(); // class
    }

    private static void EmitObjectMapping(MapperSourceBuilder sb, TypeMapping mapping)
    {
        // When a top-level converter is specified, delegate entirely to it.
        if (mapping.Converter is { } converter)
        {
            EmitConverterCall(sb, converter);
            return;
        }

        sb.AppendLine("return new " + mapping.DestinationType);
        sb.OpenBrace();

        for (int i = 0; i < mapping.MemberMappings.Count; i++)
        {
            var member = mapping.MemberMappings[i];
            string value = FormatMemberValue(member);
            sb.AppendLine(member.DestinationMember + " = " + value + ",");
        }

        sb.CloseBrace();
    }

    private static void EmitEnumMapping(MapperSourceBuilder sb, TypeMapping mapping)
    {
        sb.AppendLine("return (" + mapping.DestinationType + ")source;");
    }

    private static void EmitCollectionMapping(MapperSourceBuilder sb, TypeMapping mapping)
    {
        // Determine the inner element mapper name from the source type.
        string elementMapperName = SafeClassName(mapping.SourceType) + "ElementMapper";
        sb.AppendLine("return source.Select(" + elementMapperName + ".Map).ToList();");
    }

    private static void EmitNullableMapping(MapperSourceBuilder sb, TypeMapping mapping)
    {
        sb.AppendLine("if (source == null) return default;");
        sb.AppendLine("return (" + mapping.DestinationType + ")source;");
    }

    private static void EmitCustomMapping(MapperSourceBuilder sb, TypeMapping mapping)
    {
        if (mapping.Converter == null)
        {
            throw new InvalidOperationException(
                "Custom mapping for " + mapping.SourceType + " requires a Converter reference.");
        }

        EmitConverterCall(sb, mapping.Converter);
    }

    private static void EmitConverterCall(MapperSourceBuilder sb, ConverterRef converter)
    {
        string method = converter.MethodName ?? "Convert";
        sb.AppendLine("return " + converter.TypeName + "." + method + "(source);");
    }

    private static string FormatMemberValue(MemberMapping member)
    {
        if (member.Converter is { } converter)
        {
            string method = converter.MethodName ?? "Convert";
            return converter.TypeName + "." + method + "(source." + member.SourceMember + ")";
        }

        return "source." + member.SourceMember;
    }

    /// <summary>
    /// Produce a valid C# class name from a fully-qualified type name by
    /// replacing dots and angle brackets with underscores.
    /// </summary>
    internal static string SafeClassName(string fullyQualifiedName)
    {
        return fullyQualifiedName
            .Replace('.', '_')
            .Replace('<', '_')
            .Replace('>', '_')
            .Replace(',', '_')
            .Replace(' ', '_')
            .Replace('?', '_');
    }
}
